# This is an appspec.yml template file for use with an EC2/On-Premises deployment in CodeDeploy.
version: 0.0
# (You cannot specify both "os: linux" and "os: windows".)
os: linux

files:
  - source: /
    destination: /usr/share/nginx/html/


hooks:
# For each deployment lifecycle event, specify multiple "location" entries

  ApplicationStop:
    - location: scripts/app_stop.sh
      timeout: 300
      runas: root

# During the BeforeInstall deployment lifecycle event, run the commands
#   in the script specified in "location".
#  BeforeInstall:
#    - location: scripts/before_install.sh
#      timeout: 300
#      runas: root

# During the AfterInstall deployment lifecycle event, run the commands
#   in the script specified in "location".
#  AfterInstall:
 #   - location: scripts/after_install.sh
  #    timeout: 300
   #   runas: root

# During the ApplicationStart deployment lifecycle event, run the commands
#   in the script specified in "location".
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: root

# During the ValidateService deployment lifecycle event, run the commands
#   in the script specified in "location".
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: root

